/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-May-2022 10:25:47 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_computer_computer_room]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [computer] DROP CONSTRAINT [FK_computer_computer_room]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_account]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order] DROP CONSTRAINT [FK_order_account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_service]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order] DROP CONSTRAINT [FK_order_service]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_computer_room]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_computer_room]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_employee]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_shift]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_shift]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[account]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[computer]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [computer]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[computer_room]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [computer_room]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[employee]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[order]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [order]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[service]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [service]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[shift]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [shift]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[working_schedule]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [working_schedule]
GO

/* Create Tables */

CREATE TABLE [account]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[name] nvarchar(50) NOT NULL,
	[gender] nvarchar(50) NOT NULL,
	[phone] nvarchar(50) NOT NULL,
	[balance] float NULL,
	[email] nvarchar(50) NOT NULL,
	[username] nvarchar(50) NOT NULL,
	[password] nvarchar(50) NOT NULL,
	[role] nvarchar(50) NULL
)
GO

CREATE TABLE [computer]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[info] nvarchar(max) NULL,
	[roomID] int NOT NULL,
	[status] nvarchar(50) NOT NULL,
	[fee_per_hour] real NOT NULL,
	[macAddress] nvarchar(50) NULL
)
GO

CREATE TABLE [computer_room]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[floor] int NOT NULL,
	[compNum] int NOT NULL,
	[status] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [employee]
(
	[id] int NOT NULL,
	[name] nvarchar(50) NOT NULL,
	[position] nvarchar(50) NOT NULL,
	[birthDate] datetime NOT NULL,
	[gender] nvarchar(50) NOT NULL,
	[phoneNum] nvarchar(50) NOT NULL,
	[email] nvarchar(50) NOT NULL,
	[image] image NULL,
	[salary_per_hour] real NOT NULL,
	[username] nvarchar(50) NOT NULL,
	[password] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [order]
(
	[service_id] int NOT NULL,
	[account_id] int NOT NULL,
	[quantity] int NOT NULL
)
GO

CREATE TABLE [service]
(
	[id] int NOT NULL,
	[name] nvarchar(50) NOT NULL,
	[description] nvarchar(50) NULL,
	[price] real NOT NULL,
	[picture] image NULL
)
GO

CREATE TABLE [shift]
(
	[id] int NOT NULL,
	[startTime] time(7) NOT NULL,
	[endTime] time(7) NOT NULL,
	[week_date] nvarchar(50) NOT NULL,
	[shift_type] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [working_schedule]
(
	[shift_id] int NOT NULL,
	[employee_id] int NOT NULL,
	[date] datetime NOT NULL,
	[check_in] datetime NULL,
	[roomID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [account] 
 ADD CONSTRAINT [PK_account]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [account] 
 ADD CONSTRAINT [U_account] UNIQUE NONCLUSTERED ([username] ASC,[id] ASC)
GO

ALTER TABLE [computer] 
 ADD CONSTRAINT [PK_computer]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [computer] 
 ADD CONSTRAINT [U_computer] UNIQUE CLUSTERED ([macAddress] ASC)
GO

CREATE TRIGGER tr_computer_ForDelete
ON computer
FOR Delete
AS
BEGIN

	Declare @roomID int
	Select @roomID = roomID from deleted

	UPDATE computer_room set compNum = compNum - 1 
	WHERE @roomID = computer_room.id
END
GO

CREATE TRIGGER tr_computer_ForInsert
ON computer
FOR INSERT
AS
BEGIN

	Declare @roomID int
	Select @roomID = roomID from inserted

	UPDATE computer_room set compNum = compNum + 1 
	WHERE @roomID = computer_room.id
END
GO

ALTER TABLE [computer_room] 
 ADD CONSTRAINT [PK_computer_room]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [computer_room] 
 ADD CONSTRAINT [U_computer_room] UNIQUE CLUSTERED ([id] ASC)
GO

ALTER TABLE [employee] 
 ADD CONSTRAINT [PK_employee]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [employee] 
 ADD CONSTRAINT [U_employee] UNIQUE NONCLUSTERED ([id] ASC,[username] ASC)
GO

ALTER TABLE [order] 
 ADD CONSTRAINT [PK_order]
	PRIMARY KEY CLUSTERED ([service_id] ASC,[account_id] ASC)
GO

ALTER TABLE [service] 
 ADD CONSTRAINT [PK_service]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [shift] 
 ADD CONSTRAINT [PK_shift]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [working_schedule] 
 ADD CONSTRAINT [PK_working_schedule]
	PRIMARY KEY CLUSTERED ([shift_id] ASC,[employee_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [computer] ADD CONSTRAINT [FK_computer_computer_room]
	FOREIGN KEY ([roomID]) REFERENCES [computer_room] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [order] ADD CONSTRAINT [FK_order_account]
	FOREIGN KEY ([account_id]) REFERENCES [account] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [order] ADD CONSTRAINT [FK_order_service]
	FOREIGN KEY ([service_id]) REFERENCES [service] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_computer_room]
	FOREIGN KEY ([roomID]) REFERENCES [computer_room] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_employee]
	FOREIGN KEY ([employee_id]) REFERENCES [employee] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_shift]
	FOREIGN KEY ([shift_id]) REFERENCES [shift] ([id]) ON DELETE No Action ON UPDATE No Action
GO
