/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-May-2022 10:25:39 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[computer_room]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [computer_room]
GO

/* Create Tables */

CREATE TABLE [computer_room]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[floor] int NOT NULL,
	[compNum] int NOT NULL,
	[status] nvarchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [computer_room] 
 ADD CONSTRAINT [PK_computer_room]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [computer_room] 
 ADD CONSTRAINT [U_computer_room] UNIQUE CLUSTERED ([id] ASC)
GO