/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 13-May-2022 4:22:23 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_account]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order] DROP CONSTRAINT [FK_order_account]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_service]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order] DROP CONSTRAINT [FK_order_service]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[order]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [order]
GO

/* Create Tables */

CREATE TABLE [order]
(
	[service_id] int NOT NULL,
	[account_id] int NOT NULL,
	[quantity] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [order] 
 ADD CONSTRAINT [PK_order]
	PRIMARY KEY CLUSTERED ([service_id] ASC,[account_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [order] ADD CONSTRAINT [FK_order_account]
	FOREIGN KEY ([account_id]) REFERENCES [account] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [order] ADD CONSTRAINT [FK_order_service]
	FOREIGN KEY ([service_id]) REFERENCES [service] ([id]) ON DELETE No Action ON UPDATE No Action
GO