/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 13-May-2022 4:22:23 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[shift]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [shift]
GO

/* Create Tables */

CREATE TABLE [shift]
(
	[id] int NOT NULL,
	[startTime] DateTime NOT NULL,
	[endTime] DateTime NOT NULL,
	[week_date] nvarchar(50) NOT NULL,
	[shift_type] nvarchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [shift] 
 ADD CONSTRAINT [PK_shift]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO