/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-May-2022 10:25:40 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_computer_room]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_computer_room]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_employee]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_working_schedule_shift]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [working_schedule] DROP CONSTRAINT [FK_working_schedule_shift]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[working_schedule]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [working_schedule]
GO

/* Create Tables */

CREATE TABLE [working_schedule]
(
	[shift_id] int NOT NULL,
	[employee_id] int NOT NULL,
	[date] datetime NOT NULL,
	[check_in] datetime NULL,
	[roomID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [working_schedule] 
 ADD CONSTRAINT [PK_working_schedule]
	PRIMARY KEY CLUSTERED ([shift_id] ASC,[employee_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_computer_room]
	FOREIGN KEY ([roomID]) REFERENCES [computer_room] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_employee]
	FOREIGN KEY ([employee_id]) REFERENCES [employee] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [working_schedule] ADD CONSTRAINT [FK_working_schedule_shift]
	FOREIGN KEY ([shift_id]) REFERENCES [shift] ([id]) ON DELETE No Action ON UPDATE No Action
GO